import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}', './lib/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'background':                '#060e20',
        'surface':                   '#060e20',
        'surface-dim':               '#060e20',
        'surface-container-lowest':  '#000000',
        'surface-container-low':     '#091328',
        'surface-container':         '#0f1930',
        'surface-container-high':    '#141f38',
        'surface-container-highest': '#192540',
        'surface-bright':            '#1f2b49',
        'surface-variant':           '#192540',
        'on-surface':                '#dee5ff',
        'on-surface-variant':        '#a3aac4',
        'on-background':             '#dee5ff',
        'outline':                   '#6d758c',
        'outline-variant':           '#40485d',
        'primary':                   '#a3a6ff',
        'primary-container':         '#9396ff',
        'primary-dim':               '#6063ee',
        'primary-fixed':             '#9396ff',
        'primary-fixed-dim':         '#8387ff',
        'on-primary':                '#0f00a4',
        'on-primary-container':      '#0a0081',
        'inverse-primary':           '#494bd7',
        'surface-tint':              '#a3a6ff',
        'secondary':                 '#69f6b8',
        'secondary-dim':             '#58e7ab',
        'secondary-container':       '#006c49',
        'secondary-fixed':           '#69f6b8',
        'secondary-fixed-dim':       '#58e7ab',
        'on-secondary':              '#005a3c',
        'on-secondary-container':    '#e1ffec',
        'on-secondary-fixed':        '#00452d',
        'on-secondary-fixed-variant':'#006544',
        'tertiary':                  '#ff9dd1',
        'tertiary-dim':              '#eb7bba',
        'tertiary-container':        '#fa88c8',
        'tertiary-fixed':            '#fd8bca',
        'tertiary-fixed-dim':        '#ee7ebc',
        'on-tertiary':               '#6c0f4d',
        'on-tertiary-container':     '#5e0042',
        'on-tertiary-fixed':         '#360024',
        'on-tertiary-fixed-variant': '#6d104e',
        'error':                     '#ff6e84',
        'error-dim':                 '#d73357',
        'error-container':           '#a70138',
        'on-error':                  '#490013',
        'on-error-container':        '#ffb2b9',
        'inverse-surface':           '#faf8ff',
        'inverse-on-surface':        '#4d556b',
      },
      borderRadius: {
        DEFAULT: '0.375rem',
        sm:      '0.25rem',
        md:      '0.5rem',
        lg:      '0.75rem',
        xl:      '1rem',
        '2xl':   '1.25rem',
        '3xl':   '1.75rem',
        full:    '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
export default config
